### ISSUE TITLE
Difficult to remove all of the water

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/mean-share-and-balance#29]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/810, when the valves are open it takes me several tries to remove all of the water. The more cups that are attached, the more tries it takes me to get rid of all the water. By "tries" I mean that I am pulling the arrow down but there is still a little bit of water at the bottom of the cup. 
When the cups aren't connected, there is no issue removing all of the water. 

**Steps to reproduce**
1. Add a second cup of water to the play area
2. remove all water from one of the bottom cups
3. Open the valve between the 2-D cups
4. Empty the bottom cup of water

Repeat the above steps with more cups

**Visuals**

https://user-images.githubusercontent.com/87318828/172913312-1e1897c2-80ec-455c-ae43-7c00256ca57d.mp4

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Mean Share And Balance‬
URL: https://phet-dev.colorado.edu/html/mean-share-and-balance/1.0.0-dev.4/phet/mean-share-and-balance_all_phet.html
Version: 1.0.0-dev.4 2022-06-08 18:34:30 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/15.5 Safari/605.1.15
Language: en-US
Window: 1371x702
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 256
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by samreid** [comment]
In the commit Marla and I added support so that the slider property value can update when the thumb is being held outside the enabled range.  We added a test harness in the sun demo. And we also tested that it works well in Mean: Share and Balance itself.

We had a few questions and would like to request a code review, perhaps from someone more familiar with the accessibility side. One question we had was about whether we need to do any other cleanup outside of the end drag function. We didn't see any callbacks for drag cancel or anything like that.

We also ran a full aqua test searching for sims that are passing through the `drag` option to the slider options, and we didn't see any. The main question was if any call sites would expect the drag function to be called when the value updates in this manner. We considered adding an assertion that `drag` is not allowed anymore since we don't see any usages, but it seems like this feature was designed for usage even though it does not seem currently in use. It would be good for the reviewer to comment on this part.

@jessegreenberg do you have time to review this change?

**Comment by KatieWoe** [comment]
On Win 10 Firefox, I noticed this same behavior when trying to get all the beakers full.

**Comment by jessegreenberg** [comment]
This change looks good! I appreciate the documentation and I verified it is working well in the sun demo. My understanding is that this was only needed if the thumb is held down while the enabled range changes (while there are no events), and subsequent mouse moves would update the value correctly.

> from someone more familiar with the accessibility side.

This wasn't an issue for alt input because events continue to be received while keys are pressed down. I tested alt input with animating enabled range in the sun demo and it is working well.

>hether we need to do any other cleanup outside of the end drag function. We didn't see any callbacks for drag cancel or anything like that.

Not that I can see. `end` is called by `cancel` and `interrupt` by PressListener so it looks like that is covered.

> We considered adding an assertion that drag is not allowed anymore since we don't see any usages,

I wouldn't recommend removing this, I think it is a reasonable API to provide `start`, `end`, `drag` callbacks for the slider input even though `drag` is not currently used.

**Comment by marlitas** [comment]
Thanks for reviewing @jessegreenberg!
Keeping this issue open for the next round of QA to ensure this did indeed fix the desired behavior.

**Comment by marlitas** [comment]
Fix is merged to master. QA check on phettest to make sure it resolves the buggy behavior.

**Comment by KatieWoe** [comment]
This still happens on master. Dragging the water slows down then fully stops before the last beaker is empty. It seems better than before, but still isn't fixed. Reassigning.
![stillhappens](https://user-images.githubusercontent.com/41024075/173916546-c1cdfa81-3b69-4c71-993c-924bdf763b49.gif)

**Comment by Nancy-Salpepi** [comment]
I'm seeing the same thing as @KatieWoe. It seems the slider resists movement more and more as you near the bottom.

**Comment by marlitas** [comment]
Hmmm... Okay back to the drawing board. It's emptying on my end but is rather slow, and seems to get slower the more open pipes there are... Video is helpful to determine user interaction. Will brainstorm to find a better fix.

**Comment by pixelzoom** [comment]
While you're solving this problem... Have you tested the behavior with multi-touch? Does it behave as expected when 2 or more of the sliders are being manipulated simultaneously?

**Comment by KatieWoe** [comment]
This looks fixed to me in dev.5 and 6. The responsiveness still slows towards the end, but you can empty all the glasses.

**Comment by Nancy-Salpepi** [comment]
I see the same thing as @KatieWoe--the cups empty but it slows down. 
I was able to remove all the water with touch as well.

**Comment by marlitas** [comment]
With good feedback from QA I am closing this issue. Thanks all!

**Comment by KatieWoe** [comment]
This is already closed, but I wanted to note that some change in https://github.com/phetsims/qa/issues/835 seems to have removed this slowness entirely.
